name: Setup
description: Sets up the workspace

inputs:
  root:
    description: Where the package files are located
    default: ""
    required: false
  setup-dprint:
    description: Whether to setup dprint
    default: "false"
    required: false

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        package_json_file: ${{ inputs.root }}package.json

    - uses: actions/setup-node@v4
      with:
        node-version: "23.11.0"
        cache: "pnpm"
        cache-dependency-path: ${{ inputs.root }}pnpm-lock.yaml

    - name: install
      working-directory: ${{ inputs.root }}
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: install dprint
      if: ${{ inputs.setup-dprint }}
      working-directory: ${{ inputs.root }}
      run: |
        version=$(node -e 'const { readFile } = await import("fs/promises"); process.stdout.write(JSON.parse(await readFile("dprint.json", "utf8")).version)')
        curl -fsSL https://dprint.dev/install.sh | sh -s $version > /dev/null 2>&1
        echo "/home/runner/.dprint/bin" >> $GITHUB_PATH
      shell: bash

    - run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      shell: bash
